apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-express-hello
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/node-express-hello/node-express-hello@sha256:364074046184f5aa81f190e14fbdb23b8e60b03111e5526e38d0988b886a6251
        name: my-nodejs
        resources: {}
status: {}
